### ISSUE TITLE
no docs in pkg.go.dev

### ISSUE THREAD

**Issue by dwisiswant0** [GRbit/go-pcre#5]
Could you please define your license for this, @GRbit? Coz:

```
Documentation not displayed due to license restrictions.
```

See https://pkg.go.dev/github.com/GRbit/go-pcre.

**Comment by dwisiswant0** [comment]
> UPD: Seems like pkg.go.dev needs some time to update license info. Hope it'll display the docs soon.

I think you should create a new tag _(patch)_ for the license.

**Comment by GRbit** [comment]
Makes sense, since it also complains that go.mod is absent.
Let's see how fast they'll pull the new version.

**Comment by dwisiswant0** [comment]
It’s out now. Thanks, @GRbit!
